--TAO VIEW CHUA CAC THONG TIN CAN THIET
CREATE VIEW VW_DATA_B7 AS
SELECT VW.ID, VW.COURSE_ID, VW.POINT, C.CREDITS
FROM VW_TAKES_MAXPOINT VW JOIN COURSE C
ON VW.COURSE_ID = C.COURSE_ID
GO

--TAO VIEW CHI CHUA NHUNG MON DAT
CREATE VIEW VW_PASS AS
SELECT * FROM VW_DATA_B7 WHERE POINT > 0.5;
GO

--TAO THU TUC DE KIEM TRA HOC LUC VA TRINH DO SINH VIEN
CREATE PROCEDURE SP_CHECK_HL_TDSV (@STUDENT_ID VARCHAR(50)) AS
BEGIN
	DECLARE @SUM_CREDITS INT
    DECLARE @CPA FLOAT
	DECLARE @TCTL INT
	SELECT @SUM_CREDITS = SUM(CREDITS), @CPA = ROUND(SUM(POINT * CREDITS)/SUM(CREDITS),2)
	FROM VW_DATA_B7 WHERE ID = @STUDENT_ID
	SELECT @TCTL = SUM(CREDITS) FROM VW_PASS WHERE ID = @STUDENT_ID;
	--CHECK CONDITION TCTL
	IF @TCTL < 32 PRINT('Trinh do nam nhat');
	ELSE IF @TCTL < 64 PRINT('Trinh do nam hai');
	ELSE IF @TCTL < 96 PRINT('Trinh do nam ba');
	ELSE IF @TCTL < 128 PRINT('Trinh do nam bon');
	ELSE PRINT('Trinh do nam nam');

	--CHECK CONDITION CPA
	IF @CPA < 1 PRINT('Hoc luc kem');
	ELSE IF @CPA < 2.0 PRINT('Hoc luc yeu');
	ELSE IF @CPA < 2.5 PRINT('Hoc luc trung binh');
	ELSE IF @CPA < 3.2 AND @CPA >= 2.5 PRINT('Hoc luc kha');
	ELSE IF @CPA < 3.6 AND @CPA >= 3.2 PRINT('Hoc luc gioi');
	ELSE PRINT('Hoc luc xuat sac');

END
GO

EXEC SP_CHECK_HL_TDSV @STUDENT_ID = 93004