--TAO CAC BAN SAO CUA CAC BANG CAN DANH INDEX DE SO SANH KHI TRUY VAN
CREATE TABLE TAKES_INDEX 
(
	ID VARCHAR(5),
	COURSE_ID VARCHAR(8) ,
	SEC_ID VARCHAR(8),
	SEMESTER VARCHAR(6),
	YEAR NUMERIC(4, 0),
	GRADE VARCHAR(2),
	PRIMARY KEY(ID, COURSE_ID, SEC_ID, SEMESTER, YEAR) 
)
GO

CREATE TABLE STUDENT_INDEX 
(
	ID VARCHAR(5),
	NAME VARCHAR(20),
	DEPT_NAME VARCHAR(20),
	TOT_CRED NUMERIC(3,0),
	PRIMARY KEY(ID)
)
GO

CREATE TABLE ADVISOR_INDEX 
(
	S_ID VARCHAR(5),
	I_ID VARCHAR(5),
	PRIMARY KEY(S_ID)
)
GO

INSERT INTO dbo.TAKES_INDEX SELECT * FROM dbo.takes
INSERT INTO dbo.STUDENT_INDEX SELECT * FROM dbo.student
INSERT INTO dbo.ADVISOR_INDEX SELECT * FROM dbo.advisor
GO

--DANH CHI MUC CHO CAC BANG TAKES, STUDENT, ADVISOR
CREATE INDEX IDX_TAKES ON TAKES(GRADE);
CREATE INDEX IDX_STUDENT ON STUDENT(NAME);
CREATE INDEX IDX_ADVISOR ON ADVISOR(I_ID);
GO




