CREATE OR REPLACE PROCEDURE SP_RESULT_POINT
(
  STUDENT_ID NUMBER, 
  RESULT_CURSOR OUT SYS_REFCURSOR
) IS 
BEGIN
  OPEN RESULT_CURSOR FOR
  SELECT T.ID, S.NAME, T.SEMESTER, T.YEAR, 
  ROUND(SUM(T.POINT*C.CREDITS)/SUM(C.CREDITS), 2) GPA,
  ROUND((SELECT SUM(MAX(TN.POINT)*CC.CREDITS)/SUM(CC.CREDITS) 
  FROM VW_TAKES_NUMBER TN, COURSE CC WHERE TN.ID = STUDENT_ID
  AND TN.COURSE_ID = CC.COURSE_ID AND TN.YEAR <= T.YEAR AND TN.SEMESTER <= T.SEMESTER
  GROUP BY TN.COURSE_ID, CC.CREDITS), 2) CPA, 
  (SELECT SUM(CC.CREDITS) FROM VW_TAKES_NUMBER TN, COURSE CC
  WHERE TN.ID = STUDENT_ID AND TN.COURSE_ID = CC.COURSE_ID
  AND TN.YEAR <= T.YEAR AND TN.SEMESTER <= T.SEMESTER
  GROUP BY TN.ID) TONG_TIN_CHI
  FROM STUDENT S JOIN VW_TAKES_NUMBER T
  ON S.ID = T.ID AND T.ID = STUDENT_ID
  JOIN COURSE C ON C.COURSE_ID = T.COURSE_ID
  GROUP BY T.ID, S.NAME, T.SEMESTER, T.YEAR
  ORDER BY T.YEAR, T.SEMESTER DESC;
END;

SELECT * FROM STUDENT;

