-- BAI 1. 
--VIEW DOI DIEM CHU SANG DIEM SO
CREATE OR REPLACE VIEW VW_TAKES_NUMBER AS
SELECT ID, COURSE_ID, SEC_ID, SEMESTER, YEAR, 
  DECODE(GRADE, 'A+', 4.5, 'A ', 4.0, 'A-', 3.5, 'B+', 3.0, 'B ', 2.5, 'B-', 2.0, 
                'C+', 1.5, 'C ', 1.0, 'C-', 0.5, 0) POINT
FROM TAKES;

--VIEW LAY RA DIEM CAO NHAT
CREATE OR REPLACE VIEW VW_TAKES_MAXPOINT AS 
SELECT ID, COURSE_ID, MAX(POINT) POINT 
FROM VW_TAKES_NUMBER GROUP BY ID, COURSE_ID;

--VIEW CHUA TIN CHI TUONG UNG  
CREATE OR REPLACE VIEW VW_TAKES_CREDITS AS
SELECT VWM.ID, C.COURSE_ID, VWM.POINT, C.CREDITS 
FROM VW_TAKES_MAXPOINT VWM JOIN COURSE C
ON C.COURSE_ID = VWM.COURSE_ID;

--VIEW CHUA TONG SO TIN CHI
CREATE OR REPLACE VIEW VW_TAKES_SUMCREDITS AS 
SELECT ID, SUM(CREDITS) SUMCREDITS FROM VW_TAKES_CREDITS
WHERE POINT > 0.5 GROUP BY ID; 

--TAO THU TUC KIEM TRA DIEU KIEN TOT NGHIEP CUA SINH VIEN
CREATE OR REPLACE PROCEDURE SP_CHECK_GRADUATING (STUDENT_ID VARCHAR) AS 
SUM_CRED NUMBER; CPA NUMBER;
BEGIN
  SELECT SUMCREDITS INTO SUM_CRED FROM VW_TAKES_SUMCREDITS WHERE ID = STUDENT_ID;
  IF SUM_CRED >=  128 THEN 
    SELECT ROUND(SUM(T.POINT*C.CREDITS)/SUM(C.CREDITS),2) INTO CPA
    FROM VW_TAKES_MAXPOINT T JOIN COURSE C 
    ON T.ID = STUDENT_ID AND T.COURSE_ID = C.COURSE_ID;
    IF CPA < 1.0 THEN
      dbms_output.put_line('Khong du dieu kien tot nghiep. Diem trung binh: '||CPA);
    ELSE 
      dbms_output.put_line('Du dieu kien tot nghiep. Diem trung binh: '||CPA);  
    END IF;
  ELSE 
    dbms_output.put_line('Khong dieu kien tot nghiep. So tin chi: '||SUM_CRED);
  END IF;
  EXCEPTION
    WHEN no_data_found THEN dbms_output.put_line('Ma so sinh vien khong dung');
END;





