CREATE OR REPLACE TRIGGER T_CHECK_ROOM
BEFORE INSERT ON TAKES
FOR EACH ROW
ENABLE
DECLARE 
  MAX_CAPACITY CLASSROOM.CAPACITY%TYPE;
  CUR_CAPACITY CLASSROOM.CAPACITY%TYPE;
BEGIN
  --GET MAX CAPACITY OF CLASS
  SELECT CAPACITY INTO MAX_CAPACITY FROM CLASSROOM C JOIN SECTION S
  ON C.ROOM_NUMBER = S.ROOM_NUMBER AND S.COURSE_ID = :NEW.COURSE_ID AND
  S.SEC_ID = :NEW.SEC_ID AND S.YEAR = :NEW.YEAR AND S.SEMESTER = :NEW.SEMESTER;
  
  --GET CURRENT CAPACITY
  SELECT COUNT(*) INTO CUR_CAPACITY FROM TAKES 
  WHERE COURSE_ID = :NEW.COURSE_ID AND YEAR = :NEW.YEAR AND SEC_ID = :NEW.SEC_ID
  AND SEMESTER = :NEW.SEMESTER;
  
  --COMPARE MAX - CUR CAPACITY
  IF(MAX_CAPACITY > CUR_CAPACITY) THEN dbms_output.put_line('Lop van con trong');
  ELSE RAISE_APPLICATION_ERROR(-20990, 'Lop het cho!');
  END IF;

END;

INSERT INTO TAKES VALUES ('1000', '376', '1', 'Fall', '2006', NULL);