CREATE TRIGGER T_CHECK_ROOM
	ON TAKES 
	FOR INSERT 
AS
BEGIN
	-- DECLARE VARIABLE
	DECLARE @MAX_CAPACITY INT
	DECLARE @CUR_CAPACITY INT

	--GET MAX CAPACITY OF CLASS
	SELECT @MAX_CAPACITY = CAPACITY FROM CLASSROOM C, SECTION S, INSERTED I
	WHERE C.ROOM_NUMBER = S.ROOM_NUMBER
	AND S.COURSE_ID = I.COURSE_ID AND S.SEC_ID = I.SEC_ID
	AND S.YEAR = I.YEAR AND S.SEMESTER = I.SEMESTER;
  
	--GET CURRENT CAPACITY
	SELECT @CUR_CAPACITY = COUNT(*) FROM TAKES T, INSERTED I
	WHERE T.COURSE_ID = I.COURSE_ID AND T.YEAR = I.YEAR 
	AND T.SEMESTER = I.SEMESTER AND T.SEC_ID = I.SEC_ID;
  
	--COMPARE MAX - CUR CAPACITY
	IF(@MAX_CAPACITY > @CUR_CAPACITY) PRINT ('Lop van con cho trong');
	ELSE 
	RAISERROR('Lop het cho', 16, 1)
	ROLLBACK TRANSACTION;
END
GO


INSERT INTO TAKES VALUES ('1000', '376', '1', 'Fall', '2006', NULL);