--TAO OBJECT MOI GOM 2 TRUONG SEARCH_FIELD_NAME VAF SEARCH_VALUE
CREATE OR REPLACE TYPE SEARCH_OBJ FORCE
AS OBJECT
(
  SEARCH_FIELD_NAME VARCHAR(50),
  SEARCH_VALUE VARCHAR(50)
);

--TAO KIEU DU LIEU DANG TABLE CHO OBJECT
CREATE TYPE SEARCH_TAB IS TABLE OF SEARCH_OBJ;

--TAO THU TUC LOC DU LIEU
CREATE OR REPLACE PROCEDURE SP_LOC_DU_LIEU_3
(
  RESULT_TAB IN SEARCH_TAB,
  SEARCH_RESULT_CURSOR OUT SYS_REFCURSOR
) IS 
BEGIN
  FOR i IN 1..RESULT_TAB.COUNT
  LOOP
  IF(RESULT_TAB(i).SEARCH_FIELD_NAME = 'ID') THEN OPEN SEARCH_RESULT_CURSOR 
  FOR SELECT * FROM VW_DATA WHERE ID = RESULT_TAB(i).SEARCH_VALUE;
  ELSIF(RESULT_TAB(i).SEARCH_FIELD_NAME = 'STUDENT_NAME') THEN OPEN SEARCH_RESULT_CURSOR 
  FOR SELECT * FROM VW_DATA WHERE STUDENT_NAME = RESULT_TAB(i).SEARCH_VALUE;
  ELSIF(RESULT_TAB(i).SEARCH_FIELD_NAME = 'YEAR') THEN OPEN SEARCH_RESULT_CURSOR 
  FOR SELECT * FROM VW_DATA WHERE YEAR = RESULT_TAB(i).SEARCH_VALUE;
  ELSIF(RESULT_TAB(i).SEARCH_FIELD_NAME = 'SEMESTER') THEN OPEN SEARCH_RESULT_CURSOR 
  FOR SELECT * FROM VW_DATA WHERE SEMESTER = RESULT_TAB(i).SEARCH_VALUE;
  ELSIF(RESULT_TAB(i).SEARCH_FIELD_NAME = 'TITLE') THEN OPEN SEARCH_RESULT_CURSOR 
  FOR SELECT * FROM VW_DATA WHERE TITLE = RESULT_TAB(i).SEARCH_VALUE;
  ELSIF(RESULT_TAB(i).SEARCH_FIELD_NAME = 'ROOM_NUMBER') THEN OPEN SEARCH_RESULT_CURSOR 
  FOR SELECT * FROM VW_DATA WHERE ROOM_NUMBER = RESULT_TAB(i).SEARCH_VALUE;
  ELSIF(RESULT_TAB(i).SEARCH_FIELD_NAME = 'INSTRUCTOR_NAME') THEN OPEN SEARCH_RESULT_CURSOR 
  FOR SELECT * FROM VW_DATA WHERE INSTRUCTOR_NAME = RESULT_TAB(i).SEARCH_VALUE;
  ELSIF(RESULT_TAB(i).SEARCH_FIELD_NAME = 'DEPT_NAME') THEN OPEN SEARCH_RESULT_CURSOR 
  FOR SELECT * FROM VW_DATA WHERE DEPT_NAME = RESULT_TAB(i).SEARCH_VALUE;
  ELSIF(RESULT_TAB(i).SEARCH_FIELD_NAME = 'DAY') THEN OPEN SEARCH_RESULT_CURSOR 
  FOR SELECT * FROM VW_DATA WHERE DAY = RESULT_TAB(i).SEARCH_VALUE;
  END IF;
  END LOOP;
END;