CREATE PROCEDURE SP_REGISTER_COURSE
(
  @STUDENT_ID VARCHAR(5),
  @COURSE_ID VARCHAR(8),
  @SEC_ID VARCHAR(8),
  @YEAR NUMERIC(4,0),
  @SEMESTER VARCHAR(6)
) AS 
BEGIN TRY 
	BEGIN TRANSACTION
	INSERT INTO TAKES VALUES(@STUDENT_ID, @COURSE_ID, @SEC_ID, @SEMESTER, @YEAR, NULL);
	COMMIT TRANSACTION
END TRY
BEGIN CATCH 
	IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
	DECLARE @ERR_MESS VARCHAR(1000) = ERROR_MESSAGE()
	RAISERROR(@ERR_MESS, 16, 1)
END CATCH
RETURN 0
GO

EXEC dbo.SP_REGISTER_COURSE @STUDENT_ID = '1000', -- varchar(5)
    @COURSE_ID = '367',-- varchar(8)
    @SEC_ID = '1', -- varchar(8)
    @YEAR = 2006, -- numeric
    @SEMESTER = 'Fall' -- varchar(6)


