--TAO OBJECT MOI GOM 2 TRUONG SEARCH_FIELD_NAME VAF SEARCH_VALUE
CREATE TYPE SEARCH_TAB AS TABLE
(
  SEARCH_FIELD_NAME VARCHAR(50),
  SEARCH_VALUE VARCHAR(50)
);
GO 

--TAO THU TUC LOC DU LIEU

CREATE PROCEDURE SP_LOC_DU_LIEU_3
  @SEARCH_TAB SEARCH_TAB READONLY
AS
BEGIN
  DECLARE @COL_NAME VARCHAR(50)
  DECLARE @VAL VARCHAR(1000)
  DECLARE @i INT = 0
  DECLARE @COUNT INT;
  DECLARE @RESULT_TAB TABLE(ID INT, COL_NAME VARCHAR(50), VAL VARCHAR(50));

  INSERT INTO @RESULT_TAB SELECT ROW_NUMBER() OVER (ORDER BY SEARCH_FIELD_NAME), * 
  FROM @SEARCH_TAB;
  SELECT @COUNT = COUNT(SEARCH_FIELD_NAME) FROM @SEARCH_TAB;
  WHILE @i < @COUNT
  BEGIN
	SET @i = @i + 1	
	SELECT TOP 1 @COL_NAME = COL_NAME, @VAL = VAL FROM @RESULT_TAB
	WHERE ID = @i;
	  IF (@COL_NAME = 'ID') SELECT * FROM VW_DATA 
	  WHERE ID = @VAL
	  ELSE IF(@COL_NAME = 'STUDENT_NAME') SELECT * FROM VW_DATA 
	  WHERE STUDENT_NAME = @VAL;
	  ELSE IF(@COL_NAME = 'YEAR') SELECT * FROM VW_DATA 
	  WHERE YEAR = @VAL;
	  ELSE IF (@COL_NAME = 'SEMESTER') SELECT * FROM VW_DATA 
	  WHERE SEMESTER = @VAL;
	  ELSE IF(@COL_NAME = 'TITLE') SELECT * FROM VW_DATA 
	  WHERE TITLE =@VAL;
	  ELSE IF(@COL_NAME = 'ROOM_NUMBER') SELECT * FROM VW_DATA 
	  WHERE ROOM_NUMBER = @VAL;
	  ELSE IF(@COL_NAME = 'INSTRUCTOR_NAME') SELECT * FROM VW_DATA 
	  WHERE INSTRUCTOR_NAME = @VAL;
	  ELSE IF(@COL_NAME = 'DEPT_NAME') SELECT * FROM VW_DATA 
	  WHERE DEPT_NAME = @VAL;
	  ELSE IF(@COL_NAME = 'DAY') SELECT * FROM VW_DATA 
	  WHERE DAY = @VAL;
 END
END
GO

DECLARE @TABLE SEARCH_TAB
INSERT INTO @TABLE VALUES ('Dept_name','Physics')
EXEC dbo.SP_LOC_DU_LIEU_3 @SEARCH_TAB = @table -- SEARCH_TAB

