

SELECT LAST_NAME, SALARY, DEPARTMENT_ID FROM EMPLOYEES;

SELECT LAST_NAME FROM EMPLOYEES WHERE LAST_NAME <> 'Lorentz'
START WITH LAST_NAME = 'Lorentz'
CONNECT BY PRIOR EMPLOYEE_ID = MANAGER_ID;


SELECT LPAD(LAST_NAME, LENGTH(LAST_NAME) + (LEVEL*2)-2,'_')
AS ORG_CHART FROM EMPLOYEES START WITH LAST_NAME = 'King'
CONNECT BY PRIOR EMPLOYEE_ID = MANAGER_ID;